name: logforge
description: logforge cli - A high performance log processing toolkit written in dart
version: 1.0.0
repository: https://github.com/r4khul/logforge_cli
homepage: https://github.com/r4khul/logforge_cli
documentation: https://github.com/r4khul/logforge_cli#readme

environment:
  sdk: ^3.10.1

executables:
  logforge: logforge

dependencies:
  path: ^1.9.0
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  license_generator: ^2.1.0
